services:
  baseproject-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7294
      - ConnectionStrings__MySqlConnection=server=62.146.236.71;port=3306;database=watchers;user=watchers;password=i7pnX466Ry7D4nMr 